version: "3.7"

services:
  mysqldb:
    restart: always
    # command: --max_allowed_packet=32505856
    ports:
      - 3307:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: default
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
      MYSQL_ROOT_PASSWORD:
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD:
    volumes:
      - ./.container/5.7/database:/var/lib/mysql
      - ./config/sql:/docker-entrypoint-initdb.d/sql # Volumen donde estarán los scripts SQL
      - ./config/bash/restore-databases.sh:/docker-entrypoint-initdb.d/restore-databases.sh
    deploy:
      resources:
        limits:
          memory: 2GB
    networks:
      - global_network
